# Generated by Django 5.1.6 on 2025-02-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_category_options"),
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course")},
        ),
    ]
